name: Docker Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_run:
    workflows: ["Update scaffold"]
    types:
      - completed

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/bencher:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/bencher:latest

jobs:
  build-test-docker:
    runs-on: ubuntu-22.04

    steps:
      - run: df -h
      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
      - run: df -h
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: bencher

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: bencher
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            CACHEBUST=${{ github.sha }}

      - name: Run Docker container
        run: |
          cd bencher
          docker run -d -p 50051:50051 ${{ env.TEST_TAG }}

      - name: Checkout bencherclient code
        uses: actions/checkout@v4
        with:
          repository: 'lpapenme/bencherclient'
          ref: 'master'
          path: bencherclient

      - name: Checkout python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.2"

      - name: Install dependencies
        run: |
          cd bencherclient
          uv sync --all-groups

      - name: Run bencherclient
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd bencherclient
            # run the client, print /opt/bencher.err if it fails
            uv run python3 run_all_benchmarks.py 

      #- name: Build and push
      #  uses: docker/build-push-action@v6
      #  if: ${{ github.event_name != 'schedule' }}
      #  with:
      #    context: bencher
      #    push: true
      #    tags: ${{ env.LATEST_TAG }}
      #    cache-from: type=gha
      #    cache-to: type=gha
      #    build-args: |
      #      CACHEBUST=${{ github.sha }}

  build-test-singularity:
    runs-on: ubuntu-22.04
    needs: build-test-docker
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.4.0
      - name: build singularity container
        env:
          SINGULARITY_DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          SINGULARITY_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          apptainer build --sandbox bencher.sif container.sdef
          if [ $? -ne 0 ]; then
            echo "Singularity build failed."
            exit 1
          fi
      - name: start singularity instance
        run: |
          # start instance
          apptainer instance start bencher.sif bencher
      - name: run bencherclient
        run: |
          apptainer run instance://bencher python /opt/bencherclient/run_all_benchmarks.py